@startuml

title Diagramme de classe de l'application FlashCard

' ABDEE6

class FlashCardGame {
    
}
class FlashCard {
    -String question
    -String reponse
    }
class Pile {
    -int scoreActuel | [0,1]->pourcentage
}
class Tag {
    -String nomCateg
    -String couleur
}

FlashCardGame -- "*\nlesCartes" FlashCard
FlashCardGame -- "*\nlesPiles" Pile
Pile -- "*\nlesCartes" FlashCard
FlashCard -- "1" Tag
FlashCardGame -- "*" Tag