@startuml

title Diagramme de classe de l'application FlashCard

' ABDEE6

class FlashCardGame {
    
}
class FlashCard {
    -String question
    -String reponse
    }
class Pile {
    -int score
}
class Tag {
    -String nomCateg
    -String couleur
}

FlashCardGame -- "*\nlesPiles" Pile
FlashCard -- "1" Tag
FlashCardGame -- "*" Tag
Pile *--- "*" FlashCard

@enduml
